base_model = "google/gemini-3.5-flash"
reasoning_options = [{ type = "toggle" }, { type = "effort", values = ["low", "medium", "high"] }]

[cost]
input = 1.5
output = 9
cache_read = 0.15000000000000002

[limit]
context = 1000000
output = 65536
